

const char *lang_sq[] = { // Albanian
 "Uninstal"
,"Pajtohem me këtë patentë, dhe pranoj të gjitha sendet."
,"Objektivi:"
,"Rifresko në menuja."
,"Shto në nisje."
,"NT"
,"Gjuha:"
,"Profili Administrator:"
,"Ky version ka administratën online. Për të marrë qasje, mund të krijoni një llogari tani. Pasi të vendosni mund të shtoni, ndryshoni apo fshini llogaritë"
,"Përdoruesi:"
,"Fjalëkalimi:"
,"Instalo"
,"Anulo"
};

const char *lang_ar[] = { // Arabic
 "غير مستقر"
,"أنا أتفق مع هذه الرخصة وأنا أقبل كل الأشياء"
,"الهدف:"
,"تحديث القائمة الرئيسية"
,"أضف إلى البداية"
,"فئة الخدمات العامة"
,"اللغة:"
,"حساب مدير البرنامج:"
,"هذه النسخة لها إدارة على الإنترنت للحصول على الوصول، قد تخلق حسابا الآن. بعد وضعك يمكنك إضافة أو تغيير أو حذف الحسابات"
,"المستعمل:"
,"كلمة السر:"
,"اثبت"
,"ألغي"
};

const char *lang_az[] = { // Azerbaijani
 "Uninstall"
,"Bu lisenziya ilə razı oldum və bütün maddələri qəbul edirik."
," Target:"
,"Əsas menyuda yeni giriş."
,"Başlamaq üçün əlavə edin."
,"Qeydiyyat"
,"Dil:"
,"Komissiya hesabı:"
,"Bu versiya online idarə edir. Giriş almaq üçün, indi hesab yaratmaq ola bilərsiniz. Siz əlavə edə bilərsiniz, dəyişiklik, və ya hesabları silmək"
,"Şirkət:"
,"Qeydiyyat:"
,"Qeydiyyat"
," Cancel"
};

const char *lang_bn[] = { // Bengali
 "আন-ইনস্টল।"
,"আমি লাইসেন্সের সাথে একমত, এবং আমি সব জিনিস গ্রহণ করি।"
,"টার্গেট:"
,"প্রধান মেনুতে এন্ট্রিগুলো আপডেট করো"
,"প্রারম্ভিক বিকল্প যোগ করা হবে।"
,"NT পরিসেবা"
,"ভাষা:"
,"অ্যাডমিনিস্ট্রেটর অ্যাকাউন্ট:"
,"এই সংস্করণের অনলাইন প্রশাসন আছে। ব্যবহারের জন্য অ্যাকাউন্ট নির্মাণ করা যাবে। অ্যাকাউন্ট যোগ, পরিবর্তন অথবা মুছে ফেলার পরে"
,"ব্যবহারকারী:"
,"পাসওয়ার্ড:"
,"ইনস্টল করুন।"
,"বাতিল"
};

const char *lang_bg[] = { // Bulgarian
 "Разглоби"
,"Съгласен съм с този лиценз и приемам всичко."
,"Цел:"
,"Обновяване на въведението в главното меню."
,"Добави към старта."
,"NT Service"
,"Език:"
,"Администраторска сметка:"
,"Тази версия има онлайн администрация. За да получите достъп, може да създадете сметка сега. След настройка можете да добавяте, променяте или изтривате акаунти"
,"Потребител:"
,"Парола:"
,"Инсталиране"
,"Отмени"
};

const char *lang_zh[] = { // Chinese
 "释入"
,"我同意这份执照 我接受所有物品"
,"目标:"
,"更新主菜单中的条目 。"
,"添加为起步."
,"NT 处"
,"语言:"
,"管理员账户 :"
,"这个版本有在线管理. 要进入,你现在可能要建立一个账户。 设置后可以添加、更改或删除账户"
,"用户:"
,"密码:"
,"安装"
,"撤销。"
};

const char *lang_cs[] = { // Czech
 "Odinstalovat"
,"Souhlasím s touto licencí a přijímám všechny položky."
,"Cíl:"
,"Aktualizovat položku v hlavním menu."
,"Přidat do spuštění."
,"NT Service"
,"Jazyk:"
,"Administrativní účet:"
,"Tato verze má online administraci. Chcete-li získat přístup, můžete vytvořit účet teď. Po nastavení můžete přidat, změnit nebo smazat účty"
,"Uživatel:"
,"Heslo:"
,"Instalovat"
,"Zrušit"
};

const char *lang_da[] = { // Danish
 "Fjern installationen"
,"Jeg er enig med denne licens, og jeg accepterer alle elementer."
,"Mål:"
,"Opdatér indgang i hovedmenuen."
,"Tilføj til opstart."
,"NT Service"
,"Sprog:"
,"Administratorkonto:"
,"Denne version har online administration. For at få adgang, kan du oprette en konto nu. Efter indstilling kan du tilføje, ændre eller slette konti"
,"Bruger:"
,"Adgangskode:"
,"Installer"
,"Aflys"
};

const char *lang_nl[] = { // Dutch
 "Verwijderen"
,"Ik ben het eens met deze licentie, en ik accepteer alle items."
,"Doel:"
,"Ingang bijwerken in hoofdmenu."
,"Toevoegen aan opstarten."
,"NT Dienst"
,"Taal:"
,"Beheerdersaccount:"
,"Deze versie heeft online administratie. Om toegang te krijgen, kun je nu misschien een account aanmaken. Na instelling kunt u accounts toevoegen, wijzigen of verwijderen"
,"Gebruiker:"
,"Wachtwoord:"
,"Installeer"
,"Annuleer"
};

const char *lang_eo[] = { // Esperanto
 "Uninstall"
,"Mi konsentas kun ĉi tiu permesilo, kaj mi akceptas ĉiujn erojn."
,"Celo:"
,"Ĝisdatiga eniro en ĉefa menuo."
,"Aldonu al la komenco."
,"NT-servo"
,"Lingvo:"
,"Administrantokonto:"
,"Tiu versio havas retan administracion. Por akiri aliron, vi povas krei konton nun. Post kiam vi povas aldoni, ŝanĝi, aŭ forigi kontojn"
,"Uzanto:"
,"Pasvorto:"
,"Instali"
,"Cancel"
};

const char *lang_et[] = { // Estonian
 "Deinstallige"
,"Nõustun selle litsentsiga ja aktsepteerin kõiki esemeid."
,"Sihtmärk:"
,"Kirje uuendamine peamenüüs."
,"Lisa käivitamisele."
,"NT Service"
,"Keel:"
,"Administraatori konto:"
,"Sellel versioonil on veebihaldus. Juurdepääsu saamiseks võite nüüd konto luua. Pärast seadistamist saate kontosid lisada, muuta või kustutada"
,"Kasutaja:"
,"Parool:"
,"Paigalda"
,"Tühistage"
};

const char *lang_fi[] = { // Finnish
 "Poista asennus"
,"Olen samaa mieltä tästä lisenssistä ja hyväksyn kaikki esineet."
,"Kohde:"
,"Päivitä merkintä päävalikkoon."
,"Lisää käynnistykseen."
,"NT1"
,"Kieli:"
,"Hallintoviranomaisen tili:"
,"Tämä versio on online-hallinto. Päästäksesi käsiksi, saatat luoda tilin nyt. Asetuksen jälkeen voit lisätä, muuttaa tai poistaa tilejä"
,"Käyttäjä:"
,"Salasana:"
,"Asenna"
,"Peruuta"
};

const char *lang_fr[] = { // French
 "Désinstaller"
,"Je suis d'accord avec cette licence, et j'accepte tous les articles."
,"Objectif :"
,"Mettre à jour l'entrée dans le menu principal."
,"Ajouter au démarrage."
,"NT service"
,"Langue:"
,"Compte administrateur :"
,"Cette version a une administration en ligne. Pour y accéder, vous pourriez créer un compte maintenant. Après avoir défini, vous pouvez ajouter, modifier ou supprimer des comptes"
,"Utilisateur:"
,"Mot de passe :"
,"Installez"
,"Annuler"
};

const char *lang_de[] = { // German
 "Deinstallieren"
,"Ich stimme dieser Lizenz zu, und ich akzeptiere alle Artikel."
,"Ziel:"
,"Aktualisieren Sie den Eintrag im Hauptmenü."
,"Zum Start hinzufügen."
,"NT Service"
,"Sprache:"
,"Administratorkonto:"
,"Diese Version hat Online-Administration. Um Zugriff zu erhalten, können Sie jetzt ein Konto erstellen. Nach der Einstellung können Sie Konten hinzufügen, ändern oder löschen"
,"Benutzer:"
,"Passwort:"
,"Installieren"
,"Abbrechen"
};

const char *lang_el[] = { // Greek
 "Απεγκατάσταση"
,"Συμφωνώ με αυτή την άδεια και δέχομαι όλα τα αντικείμενα."
,"Στόχος:"
,"Ενημέρωση καταχώρησης στο κύριο μενού."
,"Προσθήκη στην εκκίνηση."
,"NT Υπηρεσία"
,"Γλώσσα:"
,"Λογαριασμός διαχειριστή:"
,"Αυτή η έκδοση έχει ηλεκτρονική διοίκηση. Για να αποκτήσετε πρόσβαση, μπορεί να δημιουργήσετε ένα λογαριασμό τώρα. Μετά τη ρύθμιση μπορείτε να προσθέσετε, να αλλάξετε ή να διαγράψετε λογαριασμούς"
,"Χρήστης:"
,"Κωδικός πρόσβασης:"
,"Εγκαταστήστε"
,"Ακύρωση"
};

const char *lang_he[] = { // Hebrew
 "הסר"
,"אני מסכים עם רישיון זה, ואני מקבל את כל הפריטים."
,"מטרה:"
,"עדכון כניסה בתפריט הראשי"
,"הוסף לסטארט-אפ."
,"שירות NT"
,"שפה:"
,"חשבון מנהל:"
,"לגרסה זו יש ניהול מקוון. כדי לקבל גישה, אתה יכול ליצור חשבון עכשיו. לאחר הגדרת באפשרותך להוסיף, לשנות או למחוק חשבונות"
,"משתמש:"
,"סיסמה:"
,"מותק"
,"ביטול"
};

const char *lang_hi[] = { // Hindi
 "स्थापना रद्द करें।"
,"मैं इस लाइसेंस से सहमत हूँ और मैं सभी वस्तुओं को स्वीकार करता हूँ।"
,"लक्ष्य:"
,"मुख्य मेनू में प्रवेश अद्यतन करें।"
,"स्टार्टअप में जोड़े।"
,"NT सेवा"
,"भाषा:"
,"व्यवस्थापक खाता:"
,"इस संस्करण में ऑनलाइन प्रशासन है। पहुँच पाने के लिए, आप अब एक खाता बना सकते हैं। सेटिंग के बाद आप खाता जोड़ सकते हैं, बदल सकते हैं या हटा सकते हैं"
,"उपयोगकर्ता:"
,"पासवर्ड:"
,"स्थापित करें"
,"रद्द करना"
};

const char *lang_hu[] = { // Hungarian
 "Kiszerelés"
,"Egyetértek ezzel az engedéllyel, és elfogadom az összes dolgot."
,"Célpont:"
,"Frissítse a bejegyzést a főmenüben."
,"Hozzáadás az indításhoz."
,"NT szolgáltatás"
,"Nyelv:"
,"Felelős számla:"
,"Ez a verzió online adminisztráció. Hogy hozzáférj, létrehozhatsz egy fiókot. A beállítás után a fiókok hozzáadása, módosítása vagy törlése"
,"Felhasználó:"
,"Jelszó:"
,"Telepítsd"
,"Törlés"
};

const char *lang_id[] = { // Indonesian
 "Batalkan"
,"Saya setuju dengan lisensi ini, dan saya menerima semua item."
,"Target:"
,"Mutakhirkan entri dalam menu utama."
,"Tambahkan ke startup."
,"Layanan NT"
,"Bahasa:"
,"Akun administrator:"
,"Versi ini memiliki administrasi online. Untuk mendapatkan akses, Anda mungkin untuk membuat akun sekarang. Setelah pengaturan Anda dapat menambahkan, mengubah, atau menghapus akun"
,"Pengguna:"
,"Sandi:"
,"Pasang"
,"Batal"
};

const char *lang_ga[] = { // Irish
 "Díshuiteáil"
,"Aontaím leis an gceadúnas seo, agus glacaim le gach mír."
,"Sprioc:"
,"Nuashonraigh iontráil sa phríomh-roghchlár."
,"Cuir le tosaithe."
,"Seirbhís NT"
,"Teanga:"
,"Cuntas riarthóir:"
,"Tá an leagan riaracháin ar líne. Chun rochtain a fháil, d'fhéadfá cuntas a chruthú anois. Tar éis a shocrú is féidir leat a chur, athrú, nó cuntais a scriosadh"
,"Úsáideoir:"
,"Pasfhocal:"
,"Suiteáil"
,"Cealaigh"
};

const char *lang_it[] = { // Italian
 "Disinstalla"
,"Sono d'accordo con questa licenza e accetto tutti gli articoli."
,"Obiettivo:"
,"Aggiorna la voce nel menu principale."
,"Aggiungi all'avvio."
,"NT1 servizio pubblico"
,"Lingua:"
,"Account amministratore:"
,"Questa versione ha amministrazione online. Per ottenere l'accesso, si potrebbe creare un account ora. Dopo l'impostazione è possibile aggiungere, modificare o eliminare gli account"
,"Utente:"
,"Password:"
,"Installa"
,"Annulla"
};

const char *lang_ja[] = { // Japanese
 "アンインストール。"
,"私はこのライセンスに同意し、すべてのアイテムを受け入れます。"
,"ターゲット:"
,"メインメニューのエントリーを更新します。"
,"スタートアップに追加"
,"NTサービス"
,"言語:"
,"管理者アカウント:"
,"このバージョンはオンライン管理を持っています。 アクセスするには、今すぐアカウントを作成してください。 設定後、アカウントの追加、変更、削除ができます。"
,"ユーザー:"
,"パスワード:"
,"インストールします。"
,"キャンセル"
};

const char *lang_ko[] = { // Korean
 "다운로드"
,"나는이 라이센스에 동의합니다, 나는 모든 항목에 동의합니다."
,"대상:"
,"본문 바로가기"
,"시작하기"
,"NT 서비스"
,"언어:"
,"관리자 계정:"
,"이 버전에는 온라인 관리가 있습니다. 액세스하려면 지금 계정을 만들 수 있습니다. 설정 후 추가, 변경, 삭제 계정"
,"사용자:"
,"비밀번호:"
,"설치"
,"이름 *"
};

const char *lang_ky[] = { // Kyrgyz
 "Түзүлбөгөн"
,"Мен бул лицензияга макулмун жана бардык пункттарды кабыл алам."
,"Максаты:"
,"Негизги менюдагы жаңыртуу."
,"Стартапка кошуңуз."
,"NT кызматы"
,"Тил:"
,"Администраторлордун эсеби:"
,"Бул версияда онлайн башкаруу бар. Кирүү үчүн, сиз азыр эсеп түзө аласыз. Түзүлгөндөн кийин эсептерди кошууга, өзгөртүүгө же өчүрүүгө болот"
,"Колдонуучу:"
,"Пароль:"
,"Орнотуу"
,"Канцел"
};

const char *lang_lv[] = { // Latvian
 "Atinstalējiet"
,"Es piekrītu šo licenci, un es pieņemu visus priekšmetus."
,"Mērķis:"
,"Atjaunināt ierakstu galvenajā izvēlnē."
,"Pievienot startam."
,"NT serviss"
,"Valoda:"
,"Administratora konts:"
,"Šī versija ir tiešsaistes administrācija. Lai piekļūtu, jūs varat tagad izveidot kontu. Pēc iestatīšanas varat pievienot, mainīt vai dzēst kontus"
,"Lietotājs:"
,"Parole:"
,"Instalējiet"
,"Atcelt"
};

const char *lang_lt[] = { // Lithuanian
 "Pašalinti"
,"Aš sutinku su šia licencija, ir aš priimti visus elementus."
,"taikinys:"
,"Atnaujinti įrašą pagrindiniame meniu."
,"@ info: whatsthis"
,"NT tarnyba"
,"Kalba:"
,"Administratoriaus sąskaita:"
,"Čia yra internetinė administracija. norėdami gauti prieigą, galite sukurti sąskaitą dabar. @ info: tooltip"
,"Naudotojas:"
,"Slaptažodis:"
,"Install"
,"Atsisakau"
};

const char *lang_ms[] = { // Malay
 "Lepaskan"
,"Aku setuju dengan lisensi ini, dan aku menerima semua barang."
,"Target:"
,"Entri Update di menu utama."
,"Tambah ke permulaan."
,"Layanan NTNoun"
,"Bahasa:"
,"Akun administrator:"
,"Versi ini memiliki administrasi online. Untuk mendapatkan akses, Anda mungkin untuk membuat akun sekarang. Setelah menetapkan Anda dapat menambahkan, mengubah, atau menghapus akun"
,"Pengguna:"
,"Kata sandi:"
,"Pasang"
,"Batal"
};

const char *lang_nb[] = { // Norwegian
 "Avinstaller"
,"Jeg er enig i denne lisensen, og jeg godtar alle elementer."
,"Mål:"
,"Oppdater oppføring i hovedmenyen."
,"Legg til i oppstart."
,"NT Service"
,"Språk:"
,"Administratorkonto:"
,"Denne versjonen har online administrasjon. For å få tilgang kan du opprette en konto nå. Etter innstilling kan du legge til, endre eller slette kontoer"
,"Bruker:"
,"Passord:"
,"Installer"
,"Avbryt"
};

const char *lang_fa[] = { // Persian
 "Uninstall"
,"من با این مجوز موافقم و همه چیز را می پذیرم."
,"هدف:"
,"ورود به منوی اصلی"
,"به استارتاپ اضافه کنید."
,"خدمات NT"
,"زبان:"
,"حساب کاربری:"
,"این نسخه دارای مدیریت آنلاین است. برای دسترسی، شما ممکن است در حال حاضر یک حساب ایجاد کنید. پس از تنظیم شما می توانید اضافه، تغییر یا حذف حساب ها"
,"کاربر:"
,"Password:"
,"نصب"
,"لغو"
};

const char *lang_pl[] = { // Polish
 "Odinstaluj"
,"Zgadzam się z tą licencją i akceptuję wszystkie przedmioty."
,"Cel:"
,"Aktualizuj wpis w menu głównym."
,"Dodaj do startu."
,"NT Serwis"
,"Język:"
,"Konto administratora:"
,"Ta wersja posiada administrację online. Aby uzyskać dostęp, możesz utworzyć konto teraz. Po ustawieniu możesz dodać, zmienić lub usunąć konta"
,"Użytkownik:"
,"Hasło:"
,"Zainstaluj"
,"Odwołaj"
};

const char *lang_pt[] = { // Portuguese
 "Desinstalar"
,"Concordo com esta licença e aceito todos os itens."
,"Alvo:"
,"Actualizar a entrada no menu principal."
,"Adicionar à inicialização."
,"NT Serviço"
,"Língua:"
,"Conta de administrador:"
,"Esta versão tem administração online. Para obter acesso, você pode criar uma conta agora. Depois de definir você pode adicionar, alterar ou excluir contas"
,"Utilizador:"
,"Senha:"
,"Instalar"
,"Cancela"
};

const char *lang_ro[] = { // Romanian
 "Dezinstalare"
,"Sunt de acord cu această licenţă şi accept toate obiectele."
,"Ţinta:"
,"Actualizează intrarea în meniul principal."
,"Adaugă la pornire."
,"Serviciul NT"
,"Limba:"
,"Contul administratorului:"
,"Această versiune are administrare online. Pentru a avea acces, ai putea crea un cont acum. După configurare puteți adăuga, modifica sau șterge conturile"
,"Utilizator:"
,"Parola:"
,"Instalează"
,"Anulează"
};

const char *lang_ru[] = { // Russian
 "Удалить"
,"Я согласен с этой лицензией и принимаю все пункты."
,"Цель:"
,"Обновление в главном меню."
,"Добавьте к стартапу."
,"Сервис NT"
,"Язык:"
,"Счет администратора:"
,"Эта версия имеет онлайн-администрирование. Чтобы получить доступ, вы можете создать учетную запись прямо сейчас. После настройки вы можете добавлять, изменять или удалять учетные записи"
,"Пользователь:"
,"Пароль:"
,"Установи"
,"Отменить"
};

const char *lang_sk[] = { // Slovak
 "Odinštalovať"
,"Súhlasím s touto licenciou a prijímam všetky položky."
,"Cieľ:"
,"Aktualizovať položku v hlavnom menu."
,"Pridať do štartu."
,"NT služba"
,"Jazyk:"
,"Účet správcu:"
,"Táto verzia má online správu. Ak chcete získať prístup, môžete si vytvoriť účet teraz. Po nastavení môžete pridať, zmeniť alebo zmazať účty"
,"Užívateľ:"
,"Heslo:"
,"Inštalovať"
,"Zrušiť"
};

const char *lang_sl[] = { // Slovenian
 "Odstrani"
,"Strinjam se s to licenco in sprejemam vse stvari."
,"Cilj:"
,"Posodobi vnos v glavnem meniju."
,"Dodaj v zagon."
,"Storitev NT"
,"Jezik:"
,"Administrativni račun:"
,"Ta različica ima spletno administracijo. Da bi dobili dostop, lahko ustvarite račun zdaj. Po nastavitvi lahko dodate, spremenite ali izbrišete račune"
,"Uporabnik:"
,"Geslo:"
,"Namesti"
,"Prekliči"
};

const char *lang_es[] = { // Spanish
 "Desinstalar"
,"Estoy de acuerdo con esta licencia, y acepto todos los artículos."
,"Meta:"
,"Actualizar la entrada en el menú principal."
,"Añadir a la startup."
,"NT Service"
,"Idioma:"
,"Cuenta Administradora:"
,"Esta versión tiene administración en línea. Para obtener acceso, puede crear una cuenta ahora. Después de configurar puede añadir, cambiar o eliminar cuentas"
,"Usuario:"
,"Contraseña:"
,"Instala"
,"Cancelar"
};

const char *lang_sv[] = { // Swedish
 "Avinstallera"
,"Jag håller med denna licens, och jag accepterar alla objekt."
,"Mål:"
,"Uppdatera inträde i huvudmenyn."
,"Lägg till i startup."
,"NT Service"
,"Språk:"
,"Administratörskonto:"
,"Denna version har online administration. För att få tillgång kan du skapa ett konto nu. Efter inställningen kan du lägga till, ändra eller ta bort konton"
,"Användare:"
,"Lösenord:"
,"Installera"
,"Avbryt"
};

const char *lang_tl[] = { // Tagalog
 "Hindi nakaluklok"
,"Sang - ayon ako sa lisensiyang ito, at tinatanggap ko ang lahat ng bagay."
,"Targe:"
,"Updated entry sa pangunahing menu."
,"Idagdag ang startup."
,"Paglilingkod ng NT"
,"Wika:"
,"Ulat ng Administrador:"
,"Ang bersyong ito ay may online administration. Upang makapasok, maaari kang lumikha ng isang salaysay ngayon. Pagkatapos mong magtakda, maaari kang magdagdag, magbago, o mag - delete ng mga account"
,"User:"
,"Password:"
,"Iluklok"
,"Cancel"
};

const char *lang_th[] = { // Thai
 "ถอนการติดตั้ง"
,"ฉันเห็นด้วยกับใบอนุญาตนี้ และฉันยอมรับทุกสิ่ง"
,"เป้าหมาย :"
,"ปรับปรุงรายการในเมนูหลัก"
,"เพิ่มไปยังการเริ่มทํางาน"
,"บริการ NT"
,"ภาษา:"
,"บัญชีผู้ดูแลระบบ:"
,"รุ่นนี้มีการบริหารออนไลน์ เพื่อเข้าถึง คุณอาจต้องสร้างบัญชีเดี๋ยวนี้ หลังจากตั้งค่าเสร็จแล้ว คุณสามารถเพิ่ม, เปลี่ยน, หรือลบบัญชีผู้ใช้ได้"
,"ผู้ใช้:"
,"รหัสผ่าน:"
,"ติดตั้ง"
,"ยกเลิก"
};

const char *lang_tr[] = { // Turkish
 "Uninstall"
,"Bu lisansı kabul ediyorum ve tüm eşyaları kabul ediyorum."
,"Hedef:"
,"Ana menüde Güncelleme girişi."
,"Başlangıç ekleyin."
,"NT Servisi"
,"Dil:"
,"Yönetici hesabı:"
,"Bu sürüm online yönetime sahiptir. Erişim almak için, şimdi bir hesap oluşturmak isteyebilirsiniz. Ekleydikten sonra, değişiklik veya hesabı silebilirsiniz"
,"Kullanıcı:"
,"Şifre:"
,"Yükleme"
,"Cancel"
};

const char *lang_uk[] = { // Ukranian
 "Видалити"
,"Я погоджуюсь з цією ліцензією, і я приймаю всі товари."
,"Мета:"
,"Оновлення в головному меню."
,"Додати до запуску."
,"Сервіс NT"
,"Мова:"
,"Рахунок адміністратора:"
,"Ця версія має онлайн-адміністрування. Щоб отримати доступ, ви можете створити обліковий запис зараз. Після налаштування можна додати, змінити або видалити облікові записи"
,"Користувач:"
,"Пароль:"
,"Встановлення"
,"Скасувати"
};

const char *lang_ur[] = { // Urdu
 "uninstall"
,"مَیں اس لائسنس سے متفق ہوں اور مَیں تمام چیزوں کو قبول کرتا ہوں ۔"
,"سوال :"
,"مین مینو ميں داخل كیجیے۔"
,"شروع کرنے میں شامل."
,"این ٹی سروس"
,"زبان:۔"
,"انتظامی حساب:"
,"اس نسخہ میں آن لائن انتظامیہ ہے۔ رسائی حاصل کرنے کے لئے، آپ اب اکاؤنٹ بنا سکتے ہیں. فیصلے کے بعد آپ کو تبدیلی، تبدیلی یا خارج کر سکتے ہیں۔"
,"صارف:۔"
,"پاس ورڈ:"
,"نصب کریں"
,"بند"
};

